name: delivery_online_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^8.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  shared_preferences: ^2.0.0
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  intl: ^0.18.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.4
  google_maps_flutter: ^2.12.3
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  google_place: ^0.4.7
  fluttertoast: ^8.2.4
  url_launcher: ^6.3.2
  socket_io_client: ^2.0.3
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
