name: delivery_online_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  shared_preferences: ^2.0.0
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  intl: ^0.18.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
